const { v4: uuidv4 } = require('uuid');

/**
 * Seed data for events
 */
module.exports = [
  {
    id: uuidv4(),
    title: 'Ramadan Charity Iftar',
    slug: 'ramadan-charity-iftar',
    description: 'Join us for a special charity iftar to raise funds for our Ramadan food distribution campaign.',
    shortDescription: 'A special charity iftar dinner to support our Ramadan humanitarian initiatives.',
    image: '/images/events/ramadan-iftar.jpg',
    startDate: new Date('2024-04-15T18:30:00'),
    endDate: new Date('2024-04-15T21:30:00'),
    location: 'Grand Ballroom',
    address: '123 Main Street',
    city: 'New York',
    country: 'USA',
    isVirtual: false,
    isActive: true,
    isFeatured: true,
    organizer: 'Ansar Humanitarian Relief',
    registrationRequired: true,
    registrationUrl: 'https://example.com/events/ramadan-iftar',
    maxAttendees: 200,
    currentAttendees: 120,
    metaTitle: 'Ramadan Charity Iftar - Ansar Humanitarian Relief',
    metaDescription: 'Join us for a special charity iftar dinner to support our Ramadan humanitarian initiatives and help provide meals to families in need.'
  },
  {
    id: uuidv4(),
    title: 'Humanitarian Aid Workshop',
    slug: 'humanitarian-aid-workshop',
    description: 'A comprehensive workshop on effective humanitarian aid delivery in crisis situations, featuring expert speakers and practical sessions.',
    shortDescription: 'Learn about effective humanitarian aid delivery from field experts.',
    image: '/images/events/humanitarian-workshop.jpg',
    startDate: new Date('2024-05-10T09:00:00'),
    endDate: new Date('2024-05-10T17:00:00'),
    location: 'Community Center',
    address: '456 Oak Avenue',
    city: 'Chicago',
    country: 'USA',
    isVirtual: false,
    isActive: true,
    isFeatured: true,
    organizer: 'Ansar Humanitarian Relief',
    registrationRequired: true,
    registrationUrl: 'https://example.com/events/humanitarian-workshop',
    maxAttendees: 50,
    currentAttendees: 35,
    metaTitle: 'Humanitarian Aid Workshop - Ansar Humanitarian Relief',
    metaDescription: 'Join our comprehensive workshop on effective humanitarian aid delivery featuring expert speakers and practical sessions.'
  },
  {
    id: uuidv4(),
    title: 'Virtual Fundraising Gala',
    slug: 'virtual-fundraising-gala',
    description: 'Our annual fundraising gala goes virtual this year! Join us online for an evening of inspiration, entertainment, and giving to support our global humanitarian projects.',
    shortDescription: 'Join our virtual gala to support humanitarian projects worldwide.',
    image: '/images/events/virtual-gala.jpg',
    startDate: new Date('2024-06-20T19:00:00'),
    endDate: new Date('2024-06-20T21:00:00'),
    isVirtual: true,
    virtualLink: 'https://example.com/virtual-gala',
    isActive: true,
    isFeatured: true,
    organizer: 'Ansar Humanitarian Relief',
    registrationRequired: true,
    registrationUrl: 'https://example.com/events/virtual-gala',
    maxAttendees: 1000,
    currentAttendees: 450,
    metaTitle: 'Virtual Fundraising Gala - Ansar Humanitarian Relief',
    metaDescription: 'Join our virtual fundraising gala for an evening of inspiration and entertainment while supporting humanitarian projects worldwide.'
  },
  {
    id: uuidv4(),
    title: 'Community Volunteer Day',
    slug: 'community-volunteer-day',
    description: 'Join us for a day of community service as we pack emergency relief kits, sort donations, and prepare materials for our international aid shipments.',
    shortDescription: 'Help pack relief kits and prepare donations for international shipments.',
    image: '/images/events/volunteer-day.jpg',
    startDate: new Date('2024-07-15T10:00:00'),
    endDate: new Date('2024-07-15T16:00:00'),
    location: 'Ansar Warehouse',
    address: '789 Industrial Parkway',
    city: 'Dallas',
    country: 'USA',
    isVirtual: false,
    isActive: true,
    isFeatured: false,
    organizer: 'Ansar Humanitarian Relief',
    registrationRequired: true,
    registrationUrl: 'https://example.com/events/volunteer-day',
    maxAttendees: 100,
    currentAttendees: 65,
    metaTitle: 'Community Volunteer Day - Ansar Humanitarian Relief',
    metaDescription: 'Volunteer with us to pack emergency relief kits and prepare donations for our international humanitarian aid shipments.'
  },
  {
    id: uuidv4(),
    title: 'Water Crisis Awareness Webinar',
    slug: 'water-crisis-awareness-webinar',
    description: 'Join our expert panel for an informative webinar on the global water crisis, its impact on vulnerable communities, and sustainable solutions being implemented.',
    shortDescription: 'Learn about the global water crisis and sustainable solutions from our expert panel.',
    image: '/images/events/water-webinar.jpg',
    startDate: new Date('2024-08-22T18:00:00'),
    endDate: new Date('2024-08-22T19:30:00'),
    isVirtual: true,
    virtualLink: 'https://example.com/water-webinar',
    isActive: true,
    isFeatured: false,
    organizer: 'Ansar Humanitarian Relief',
    registrationRequired: true,
    registrationUrl: 'https://example.com/events/water-webinar',
    maxAttendees: 500,
    currentAttendees: 210,
    metaTitle: 'Water Crisis Awareness Webinar - Ansar Humanitarian Relief',
    metaDescription: 'Join our webinar to learn about the global water crisis, its impact on communities, and sustainable solutions being implemented.'
  }
]; 